blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/akaalcreatives/librediary#readme
    about: Check out the documentation before opening an issue
  - name: Discussions
    url: https://github.com/akaalcreatives/librediary/discussions
    about: Ask questions and discuss ideas
